TEXT = (
    ('Hey', 'Hey'),
    ('Hi', 'Hi'),
    ('What s your name?', 'What s your name?'),
    ('How are you?', 'How are you?'),
    ('How old are you?', 'How old are you?'),
    ('Nice to meet you', 'Nice to meet you'),
    ('Where are you from?', 'Where are you from?'),
    ('What kind of food do you like?', 'What kind of food do you like?'),
    ('Can I call you now?', 'Can I call you now?'),
    ('Can we have a video call with you now?', 'Can we have a video call with you now?'),
    ('What is you favourite cartoon?', 'What is you favourite cartoon?'),
    ('What is your education?', 'What is your education?'),
    ('Is it possible to be friends?', 'Is it possible to be friends?'),
    ('Goodbye! See you!', 'Goodbye! See you!'),
    ('Have a nice day!', 'Have a nice day!'),
)

ANSWER = (
    ('Hi! How are you?', 'Hi! How are you?'),
    ('Hi! Welcome to my chat', 'Hi! Welcome to my chat'),
    ('I m Bob', 'I m Bob'),
    ('I m fine, thank you', 'I m fine, thank you'),
    ('I m 25 years old', 'I m 25 years old'),
    ('Me too', 'Me too'),
    ('I m from United States', 'I m from United States'),
    ('I love pizza!', 'I love pizza!'),
    ('Yes! I m waiting for your call!!!', 'Yes! I m waiting for your call!!!'),
    ('Yes, of course', 'Yes, of course'),
    ('My favourite cartoon is Lion King', 'My favourite cartoon is Lion King'),
    ('I m in high school in London', 'I m in high school in London'),
    ('Yes, of course. Let s become friends', 'Yes, of course. Let s become friends'),
    ('See you again', 'See you again'),
    ('Thank you for this chat, you too!', 'Thank you for this chat, you too!'),
)
